# Generated by Django 5.2.17 on 2026-10-04 16:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='plate',
            field=models.CharField(default='', max_length=9, validators=[django.core.validators.RegexValidator(message='La plaque doit respecter le format AA-123-AA.', regex='^[A-Z]{2}-\\d{3}-[A-Z]{2}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('plate',), name='unique_active_reservation_per_plate'),
        ),
    ]
