# Generated by Django 5.2.17 on 2026-10-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
