# Generated by Django 5.2.17 on 2026-10-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parking_latitude_parking_longitude'),
        ('parking', '0002_reservation_ended_at_reservation_plate_and_more'),
    ]

    operations = [
    ]
