# Generated by Django 5.2.17 on 2026-10-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_merge_20261006_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='closing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='heure de fermeture'),
        ),
        migrations.AddField(
            model_name='parking',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='tarif horaire (€)'),
        ),
        migrations.AddField(
            model_name='parking',
            name='max_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text="Laisser vide si la durée n'est pas limitée.", null=True, verbose_name='durée maximale (minutes)'),
        ),
        migrations.AddField(
            model_name='parking',
            name='opening_time',
            field=models.TimeField(blank=True, help_text="Laisser vide avec l'heure de fermeture si le parking est ouvert 24h/24.", null=True, verbose_name="heure d'ouverture"),
        ),
    ]
