# Generated by Django 5.2.17 on 2026-10-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_parking_pricing'),
        ('parking', '0004_reservation_unique_active_reservation_per_spot'),
    ]

    operations = [
    ]
