# Generated by Django 5.2.17 on 2026-10-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_merge_20261008_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], default='active', max_length=10),
        ),
    ]
